site_name: Backpropagate
site_url: https://backpropagate.github.io/notes
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

  # Fonts and Codes
  font:
    text: Merriweather Sans
    code: Red Hat Mono

  # Icon
  icon:
    logo: fontawesome/solid/b

  # footer
  features:
    - navigation.footer

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

# extra:
#   social:
#     - icon: simple/youtube
#       link: https://youtube.com/@james-willett
#     - icon: simple/linkedin
#       link: https://linkedin.com/in/willettjames

copyright: Copyright &copy; 2025 Harish Gehlot

